### PR TITLE
Support for modern Python (3.4, 3.5) and Django (>1.8) versions

### PR DESCRIPTION
**Pull request by barseghyanartur**
Tested with:

- Python 2.7, 3.4 and 3.5.
- Django 1.6, 1.7, 1.8, 1.9, 1.10 and 1.11.

Summary of changes:

- Reworked test settings.
- Minor changes in the code for Django and Python3 compatibility.
- Sorted imports.
- Updated tox.
- Python 3 support (via six bundled into Django).
- Updated travis config.

### CODE REVIEW

**Comment by barseghyanartur** [comment]
@pipermerriam:

Any estimations on when the merge could/would be done?

**Comment by barseghyanartur** [comment]
@pipermerriam:

Ping (just reminding about this pull request).

**Comment by pipermerriam** [comment]
Hi @barseghyanartur 

This isn't a library I'm able to keep maintained.  I would suggest working off of your own fork and/or a new package if you'd like to do releases on pypi.  I'll happily point the readme for this repo at such a project if you're inclined to take that on.

**Comment by jxcl** [comment]
@barseghyanartur I believe (but am not sure) that Django-Ogmios is similar to this project. It is still maintained. https://github.com/fusionbox/django-ogmios

**Comment by barseghyanartur** [comment]
@pipermerriam:

Fine. Do you think you could grant me access to the PyPI?

Username: delusionalinsanity.

Thanks.

@jxcl:

It's about an existing project, that I'm upgrading from one version to Django to another. I want to make it more sustainable (for future upgrades).

**Comment by pipermerriam** [comment]
@barseghyanartur I'm not comfy handing the package over as I don't know you and it could open up any current users of the package to a security issue were you to be untrustworthy.

If you'd like to register a different package I'll link to it in the readme of this project and we could see about a full hand-over somewhere down the line.

**Comment by barseghyanartur** [comment]
@pipermerriam:

You amaze me, man. Check my GitHub profile. Would an untrustworthy person spend years on GitHub to risk his reputation on a package like this?

**Pull request closed without merging**
