### PR TITLE
fix mutable function default argument

### PR DESCRIPTION
**Pull request by pipermerriam**
One of the methods of `emailtools.cbe.mixins.UserTokenEmailMixin` had a mutable argument.  I removed it.

42132895_scaled_372x480

### CODE REVIEW

**Comment by rockymeza** [comment]
Test failures seem unrelated:

https://travis-ci.org/fusionbox/django-emailtools/jobs/52227124

**Comment by pipermerriam** [comment]
I'll fix them.

**Comment by pipermerriam** [comment]
This should fix the deprecation errors.

**Comment by pipermerriam** [comment]
I updated the `tox/.travis.yml` config with the *new* style that I've been using to keep the two closer in sync with each other.  This eliminated the need for #10  as well.

**Comment by pipermerriam** [comment]
Interesting.  in 9752fc3 I converted travis to run it's tests within tox.  On my local machine, this works just fine, but on travis, the `importlib` install fails.

**Comment by pipermerriam** [comment]
Reverted the tox changes.  This should pass.

**Pull request merged**
