### PR TITLE
Added more Django versions to the build matrix

### PR DESCRIPTION
**Pull request by thedrow**
This package should probably support more Django versions.
1.3 is no longer supported so I'm not sure if we want to keep supporting it ourselves.

### CODE REVIEW

**Comment by thedrow** [comment]
Some of the failures are simple deprecations.
The Django 1.7 failure is something that is probably related to the test suite and is easy to fix.
I'd give it a shot later if anyone else won't beat me to it.

**Comment by pipermerriam** [comment]
:+1: 

> 1.3 is no longer supported so I'm not sure if we want to keep supporting it ourselves.

I don't see any problem removing 1.3 support.

**Comment by pipermerriam** [comment]
The `1.7` failure is because of https://github.com/fusionbox/django-emailtools/blob/master/emailtools/cbe/mixins.py#L2

The import of `Site` just needs to be moved into the method call(s) that use it.

**Comment by thedrow** [comment]
I need #6 and this PR merged before I can tackle #9 and #11.

**Comment by pipermerriam** [comment]
#6 is merged.

**Pull request merged**
